### PR TITLE
Merge branch with_domains2 into master

### PR DESCRIPTION
**Pull request by lemoer**

### CODE REVIEW

**Comment by lemoer** [comment]
Does anyone have objections?

**Comment by AiyionPrime** [comment]
Was ist mit dem nextnode-section Konflikt?

**Comment by lemoer** [comment]
The `next_node` section in the site.conf can be removed. It's now part of the domain configs. The reason why I didn't do it yet, was that it has to be done directly toghether with merging.

**Comment by 1977er** [comment]
Please, go ahead.

**Comment by lemoer** [comment]
Done. I also changed the site_branch default value in jenkins to 'master' in all projects.

**Comment by AiyionPrime** [comment]
Thanks

**Pull request merged**
