### PR TITLE
move services to {opkg,firmware,ntp}.ffh.zone

### PR DESCRIPTION
**Pull request by lemoer**
Please review carefully, because if we fail here, we probably have to flash 900 routers manually.

### CODE REVIEW

**Review by tobby88 — APPROVED** [review]
looks good

**Comment by lemoer** [comment]
`opkg.ffh.zone` is not working yet. The change prepares future use.

**Review by AiyionPrime — APPROVED** [review]
I, me and myself approve this.

**Comment by lemoer** [comment]
Okay. I think two reviews should be enough. I'll merge this now, so we can build a new firmware.

**Pull request merged**
