### PR TITLE
fastd: move mtu section

### PR DESCRIPTION
**Pull request by AiyionPrime**

### CODE REVIEW

**Comment by 1977er** [comment]
Syntactically looks good. But I have no idea, if it's semantically correct.

**Comment by 1977er** [comment]
Syntactically looks good. But I have no idea, if it's semantically correct.

**Comment by AiyionPrime** [comment]
> Syntactically looks good. But I have no idea, if it's semantically correct.

Just tested, it is.

**Review by lemoer — APPROVED** [review]
LGTM.

**Comment by AiyionPrime** [comment]
Well, no need to merge this then.
@Dark4MD committed the change as well... 0add3afd038869b29ada2e17386ad0b972360582

**Pull request closed without merging**
