### PR TITLE
Merge Master changes into Stable branch

### PR DESCRIPTION
**Pull request by Dark4MD**
After the Release of Gluon v2022.1 there was a lot of changes that needs to go into the stable site branch for builing.

### CODE REVIEW

**Comment by lemoer** [comment]
These changes do look good to me.

**Comment by lemoer** [comment]
Did you have a look on the `master-wireguard` branch, if there are things, which should be picked as well?

**Comment by AiyionPrime** [comment]
I still think we should not merge this, but reset as I described in #freifunkh earlier.

**Comment by Dark4MD** [comment]
I would support @AiyionPrime approach cause stable was always a branch of master to enable stable releases while gluon master had already major changes to site specific things.
But i still wanted to create this pr as an option to look into and discuss.

Nevermind Master and Master-Wireguard are ok. Just missing the wireguard Autoupdater setting

**Comment by AiyionPrime** [comment]
We reset 24 days ago, this is done, I think.

**Pull request closed without merging**
